### ISSUE TITLE
:(

### ISSUE THREAD

**Issue by darkdarcool** [JBYT27/Dying-Sim#1]
No ConsoleHelp module? ME SAD
(this is meant as a joke lol)

**Comment by JBYT27** [comment]
Ummm wat?

**Comment by darkdarcool** [comment]
The module I made that you're helping with?

**Comment by JBYT27** [comment]
Yeah. Ik that, but wdym by it was a joke?

**Comment by JBYT27** [comment]
ohhhh, ok. got it ;) uhh, but why would i use it in this tho?

**Comment by darkdarcool** [comment]
It good, is has typing animation.

**Comment by darkdarcool** [comment]
go to the DarkScript Compiler repl
